[
{
     "_id":"APPDB-TS-1654318172-yRDdok",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318172",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318173-252BPi",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318173",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318174-IU4hED",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318174",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318175-pRuXtY",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318175",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318176-XvWUNe",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318176",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318177-lWvKBP",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318177",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318178-Uat2Kp",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318178",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318179-B9At08",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318179",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318180-8B7Mbf",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318180",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318181-QM6hP9",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318181",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318182-20LFfi",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318182",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318183-cxkhjL",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318183",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318184-PihYdA",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318184",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318185-HB17in",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318185",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318186-8TuDQ4",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318186",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318187-7NEtOt",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318187",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318188-46ugGc",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318188",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318189-0RHWdG",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318189",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318190-d5Gj1n",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318190",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
{
     "_id":"APPDB-TS-1654318191-X1lJ1X",
     "category":"SUMMARY",
     "nick-name":"PSQ_SCORE",
     "properties":{
         "psq_createtime":"1654318191",
         "psq_score":"null",
         "psq_created_time":"null",
         "psq_updated_time":"null",
         "psq_threshold":"null",
         "psq_quality":"null",
         "psq_square":"null"
         }
},
]
