[
{
     "_id":"APPDB-DS-1653452535-XPdMOU",
     "category":"PLANNING",
     "nick-name":"PSG_GUN_IMAGE",
     "properties":{
         "PSG_GUNNAME":"S20R01GUN01",
         "PSG_GUN_IMAGE1":"gunlayout.png",
         "PSG_POS_L":"39.6",
         "PSG_POS_T":"25.8",
         "PSG_MODULE_NAME":"S20R01T01",
         "PSG_MODULE_ID":"0",
         "PSI_GROUP_ID":"SNG20"
         }
},
{
     "_id":"APPDB-DS-1653452536-Egajwu",
     "category":"PLANNING",
     "nick-name":"PSG_GUN_IMAGE",
     "properties":{
         "PSG_GUNNAME":"S20R01GUN02",
         "PSG_GUN_IMAGE1":"gunlayout.png",
         "PSG_POS_L":"38.4",
         "PSG_POS_T":"52.9",
         "PSG_MODULE_NAME":"0",
         "PSG_MODULE_ID":"0",
         "PSI_GROUP_ID":"0"
         }
},
{
     "_id":"APPDB-DS-1653452537-aTQxWg",
     "category":"PLANNING",
     "nick-name":"PSG_GUN_IMAGE",
     "properties":{
         "PSG_GUNNAME":"S20R01GUN03",
         "PSG_GUN_IMAGE1":"gunlayout.png",
         "PSG_POS_L":"58.4",
         "PSG_POS_T":"46.2",
         "PSG_MODULE_NAME":"0",
         "PSG_MODULE_ID":"0",
         "PSI_GROUP_ID":"0"
         }
},
{
     "_id":"APPDB-DS-1653452538-flv9fJ",
     "category":"PLANNING",
     "nick-name":"PSG_GUN_IMAGE",
     "properties":{
         "PSG_GUNNAME":"S20R01GUN04",
         "PSG_GUN_IMAGE1":"gunlayout.png",
         "PSG_POS_L":"54.3",
         "PSG_POS_T":"70.6",
         "PSG_MODULE_NAME":"0",
         "PSG_MODULE_ID":"0",
         "PSI_GROUP_ID":"0"
         }
}
]
