[
{
     "category":"HKH",
     "nick-name":"SPOT",
     "properties":{
         "pageSize": 1, 
         "PSL_CREATETIME": 1648106126.853,
         "PSL_SPOTINDEX": 9,
         "PSL_SPOTTIME": "2022-03-24 15:15:24",
         "PSL_TRIGGERTYPE": 4,
         "PSL_DURATION": 885,
         "PSL_SENSORINFO": 1,
         "PSL_ID": 180406,
         "PSL_INLETPRESSURE": 0,
         "PSL_BACKPRESSURE": 0,
         "PSL_WATERFLOW1": 11.111,
         "PSL_WATERFLOW2": 3.5,
         "PSL_WATERFLOW3": 3.681,
         "PSL_TEMPERATURE1": 19.1,
         "PSL_TEMPERATURE2": 0,
         "PSL_TEMPERATURE3": 0,
         "PSL_TEMPERATURE4": 0,
         "PSL_TEMPERATURE5": 0,
         "PSL_TEMPERATURE6": 0,
         "PSL_TEMPERATURE7": 0,
         "PSL_TEMPERATURE8": 0,
         "PSL_XAXISANGLE": 0,
         "PSL_YAXISANGLE": 0,
         "PSL_ZAXISANGLE": 0,
         "PSL_AVERAGECURRENT": 10046,
         "PSL_AVERAGEVOLTAGE1": 1413,
         "PSL_AVERAGEVOLTAGE2": 0,
         "PSL_AVERAGEPRESSURE1": 2194,
         "PSL_AVERAGEPRESSURE2": 0,
         "PSL_COLLECTORIP": "10.208.106.204",
         "PSL_WORKPIECEID": "JNQK_31_171001801_202203240832_0000000000000000820",
         "PSL_MODEL": "820",
         "PSL_SEQUENCEID": 9,
         "PSL_POWER": 10046,
         "PSQ_SCORE": None,
         "PSQ_THRESHOLD": None,
         "PSQ_QUALITY": None,
         "PSQ_SQUARE": None,
         "XAL_QUALITY": "OK",
         "XAL_QVALUE": "0.871604 ",
         "XAL_QTHRESHOLD": "0.000000 ",
         "XAL_CURRENTPROGRAM": "3 ",
         "XAL_CURRENTSPOT": "31-11_JNZQ_031_0011 ",
         "XAL_GUNNAME": "FD010R01G01 ",
         "XAL_MILLINGSPOTCOUNT": 0,
         "XAL_MILLINGCYCLECOUNT": 0,
         "PSI_SPOT_IMAGE1": "LZ1613158003宽体前围内板分总成.png",
         "PSI_SPOT_IMAGE2": "LZ1613158003宽体前围内板分总成.png",
         "PSI_POS_L": 45.1,
         "PSI_POS_T": 5.5,
         "PSG_GUN_IMAGE1": "gunlayout_JNQK_01.png",
         "PSG_POS_L": 50.9,
         "PSG_POS_T": 36.6
         }
},

{
     "category":"HKH",
     "nick-name":"SPOT",
     "properties":{
         "pageSize": 2, 
         "PSL":{
             "PSL_CREATETIME": 1648106126.853,
             "PSL_SPOTINDEX": 9,
             "PSL_SPOTTIME": "2022-03-24",
             "PSL_TRIGGERTYPE": 4,
             "PSL_DURATION": 885,
             "PSL_SENSORINFO": 1,
             "PSL_ID": 180406,
             "PSL_INLETPRESSURE": 0,
             "PSL_BACKPRESSURE": 0,
             "PSL_WATERFLOW1": 11.111,
             "PSL_WATERFLOW2": 3.5,
             "PSL_WATERFLOW3": 3.681,
             "PSL_TEMPERATURE1": 19.1,
             "PSL_TEMPERATURE2": 0,
             "PSL_TEMPERATURE3": 0,
             "PSL_TEMPERATURE4": 0,
             "PSL_TEMPERATURE5": 0,
             "PSL_TEMPERATURE6": 0,
             "PSL_TEMPERATURE7": 0,
             "PSL_TEMPERATURE8": 0,
             "PSL_XAXISANGLE": 0,
             "PSL_YAXISANGLE": 0,
             "PSL_ZAXISANGLE": 0,
             "PSL_AVERAGECURRENT": 10046,
             "PSL_AVERAGEVOLTAGE1": 1413,
             "PSL_AVERAGEVOLTAGE2": 0,
             "PSL_AVERAGEPRESSURE1": 2194,
             "PSL_AVERAGEPRESSURE2": 0,
             "PSL_COLLECTORIP": "10.208.106.204",
             "PSL_WORKPIECEID": "JNQK_31_171001801_202203240832_0000000000000000820",
             "PSL_MODEL": "820",
             "PSL_SEQUENCEID": 9,
             "PSL_POWER": 10046
         },
         "PSQ":{
             "PSQ_SCORE": None,
             "PSQ_THRESHOLD": None,
             "PSQ_QUALITY": None,
             "PSQ_SQUARE": None,
         },
         "XAL":{
             "XAL_QUALITY": "OK",
             "XAL_QVALUE": "0.871604 ",
             "XAL_QTHRESHOLD": "0.000000 ",
             "XAL_CURRENTPROGRAM": "3 ",
             "XAL_CURRENTSPOT": "31-11_JNZQ_031_0011 ",
             "XAL_GUNNAME": "FD010R01G01 ",
             "XAL_MILLINGSPOTCOUNT": 0,
             "XAL_MILLINGCYCLECOUNT": 0,
         },
         "PSI":{
             "PSI_SPOT_IMAGE1": "LZ1613158003宽体前围内板分总成.png",
             "PSI_SPOT_IMAGE2": "LZ1613158003宽体前围内板分总成.png",
             "PSI_POS_L": 45.1,
             "PSI_POS_T": 5.5,
         },
         "PSG":{
             "PSG_GUN_IMAGE1": "gunlayout_JNQK_01.png",
             "PSG_POS_L": 50.9,
             "PSG_POS_T": 36.6
         }
     }
},

{
     "category":"HKH",
     "nick-name":"SPOT",
     "properties":{
         "pageSize": 3, 
         "PSL":{
             "PSL_CREATETIME": 1648106126.853,
             "PSL_SPOTINDEX": 9,
             "PSL_SPOTTIME": "2022-03-24 15:15:24",
             "PSL_TRIGGERTYPE": 4,
             "PSL_DURATION": 885,
             "PSL_SENSORINFO": 1,
             "PSL_ID": 180406,
             "PSL_INLETPRESSURE": 0,
             "PSL_BACKPRESSURE": 0,
             "PSL_WATERFLOW": [
                 11.111,
                 3.5,
                 3.681
             ],
             "PSL_TEMPERATURE": [
                 19.1,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0,
                 0
             ],
             "PSL_XAXISANGLE": 0,
             "PSL_YAXISANGLE": 0,
             "PSL_ZAXISANGLE": 0,
             "PSL_AVERAGECURRENT": 10046,
             "PSL_AVERAGEVOLTAGE1": 1413,
             "PSL_AVERAGEVOLTAGE2": 0,
             "PSL_AVERAGEPRESSURE1": 2194,
             "PSL_AVERAGEPRESSURE2": 0,
             "PSL_COLLECTORIP": "10.208.106.204",
             "PSL_WORKPIECEID": "JNQK_31_171001801_202203240832_0000000000000000820",
             "PSL_MODEL": "820",
             "PSL_SEQUENCEID": 9,
             "PSL_POWER": 10046
         },
         "PSQ":{
             "PSQ_SCORE": None,
             "PSQ_THRESHOLD": None,
             "PSQ_QUALITY": None,
             "PSQ_SQUARE": None,
         },
         "XAL":{
             "XAL_QUALITY": "OK",
             "XAL_QVALUE": "0.871604 ",
             "XAL_QTHRESHOLD": "0.000000 ",
             "XAL_CURRENTPROGRAM": "3 ",
             "XAL_CURRENTSPOT": "31-11_JNZQ_031_0011 ",
             "XAL_GUNNAME": "FD010R01G01 ",
             "XAL_MILLINGSPOTCOUNT": 0,
             "XAL_MILLINGCYCLECOUNT": 0,
         },
         "PSI":{
             "PSI_SPOT_IMAGE1": "LZ1613158003宽体前围内板分总成.png",
             "PSI_SPOT_IMAGE2": "LZ1613158003宽体前围内板分总成.png",
             "PSI_POS_L": 45.1,
             "PSI_POS_T": 5.5,
         },
         "PSG":{
             "PSG_GUN_IMAGE1": "gunlayout_JNQK_01.png",
             "PSG_POS_L": 50.9,
             "PSG_POS_T": 36.6
         }
     }
}

]